wheel_radius: 0.033 # radius of the wheels
track_width: 0.16 # distance between the wheels
collision_radius: 0.11 # collision radius of base_link
motor_cmd_to_radsec: 0.024 # rad/s per command interval
motor_cmd_max: 256 # maximum command speed
encoder_ticks_to_rad: 0.00153398078 # radians per encoder tick
odom: "odom"  # the name of the odometry frame
body: "blue-base_footprint"  # the name of the body frame of the robot
left_wheel: "red-wheel_left_joint" # the name of left wheel joint
right_wheel: "red-wheel_right_joint" # the name of right wheel joint