wheel_radius: 0.033 # radius of the wheels
track_width: 0.16 # distance between the wheels
collision_radius: 0.11 # collision radius of base_link
motor_cmd_to_radsec: 0.026 # rad/s per command interval
motor_cmd_max: 256 # maximum command speed
encoder_ticks_to_rad: 0.00024414062 # radians per encoder tick