x0: -0.6                       # initial x-coordinate of the robot
y0: 0.8                        # initial y-coordinate of the robot
theta0: 1.57                   # initial theta of the robot
cylinder_xs: [-0.6,0.6,0.6]    # list of x-coordinates of the cylinders
cylinder_ys: [-0.8,-0.8,0.8]   # list of y-coordinates of the cylinders
cylinder_r: 0.038              # radius of the cylinder
cylinder_h: 0.25               # height of the cylinder

